resources_group          = "ARM"
ado_org                  = "https://dev.azure.com/apexdatahub"
ado_project              = "ARM_ML"
github_repository        = "raaedserag/apex-iac-test"
github_branch            = "design"
pipeline_definition_path = "devops/dev/ci.yml"
